import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import JSZip from 'jszip';
import { internalMediaDispatchOrigin, mediaZipFilename, validWorkerSignature, verifyMediaBytes, workerInvocationSignature } from './admin-media-backup-utils';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

const root = resolve(import.meta.dirname, '..');
const read = (name: string) => readFileSync(resolve(root, name), 'utf8');
const background = read('admin-media-backup-background.ts');
const start = read('admin-start-media-backup.ts');
const status = read('admin-media-backup-status.ts');
const download = read('admin-media-backup-download.ts');
const utils = read('lib/admin-media-backup-utils.ts');
const migration = read('../../../supabase/migrations/20260810_add_backup_jobs.sql');
const frontend = read('../../src/pages/BackupCenter.tsx');
assert.match(start, /BACKUP_WORKER_SECRET[\s\S]*before|BACKUP_WORKER_SECRET/);
assert.match(start, /workerInvocationSignature\(workerSecret, jobId, actorUserId, expiresAt\)/);
assert.match(start, /internalMediaDispatchOrigin\(event\)/);
assert.match(start, /admin-media-backup-background/);
assert.match(start, /start\.status !== 202/);
assert.match(start, /media_backup_dispatch_start/);
assert.match(start, /media_backup_dispatch_result/);
assert.match(start, /dispatch_fetch_failed/);
assert.match(start, /AbortSignal\.timeout\(12_000\)/);
assert.doesNotMatch(start, /process\.env\.URL \|\| process\.env\.DEPLOY_PRIME_URL/);
assert.match(background, /event\.httpMethod !== 'POST'/);
assert.match(background, /validWorkerSignature\(workerSecret, body\.job_id, body\.actor_user_id, body\.expires_at, body\.signature\)/);
assert.match(background, /eq\('actor_user_id', body\.actor_user_id\)\.eq\('estado', 'pending'\)/);
assert.match(background, /fotos-reportes\\\/firmas/);
assert.match(background, /storage\.from\(SIGNATURE_BUCKET\)\.download/);
assert.match(background, /fecha_trabajo, fotos_urls/);
assert.match(background, /mediaZipFilename/);
assert.match(background, /references\.sort/);
assert.match(background, /fecha_trabajo: ref\.fecha_trabajo/);
assert.doesNotMatch(background, /image\/gif/);
assert.doesNotMatch(utils, /image\/gif/);
for (const mime of ['image/jpeg', 'image/png', 'image/webp', 'application/pdf']) assert.match(background, new RegExp(mime));
assert.match(utils, /createHmac\('sha256'/); assert.match(utils, /timingSafeEqual/);
assert.match(utils, /internalMediaDispatchOrigin/);
assert.match(utils, /allowedMediaOrigin\(url\.origin\) === url\.origin/);
assert.match(download, /const expectedPathPrefix = `media-jobs\/\$\{body\.job_id\}\//);
assert.match(download, /storage_bucket !== MEDIA_BUCKET/); assert.match(download, /createSignedUrl\(data\.storage_path, 15 \* 60\)/);
assert.match(status, /requireActiveAdministrator/); assert.doesNotMatch(frontend, /SUPABASE_SERVICE_ROLE_KEY|VITE_SUPABASE_SERVICE_ROLE_KEY/);
assert.match(status, /parseJsonBody\(event, \['job_id'\]\)/);
assert.match(status, /body\.job_id !== undefined/);
assert.match(status, /eq\('id', body\.job_id\)\.eq\('actor_user_id', actorUserId\)/);
assert.match(status, /eq\('actor_user_id', actorUserId\)\.eq\('tipo', 'media'\)\.in\('estado', activeStates\)/);
assert.match(status, /order\('created_at', \{ ascending: false \}\)/);
assert.match(status, /\{ active_job: null \}/);
assert.match(status, /\['pending', 'preparing', 'downloading', 'compressing', 'verifying'\]/);
assert.doesNotMatch(status, /storage_bucket/);
assert.doesNotMatch(status, /storage_path: data\.storage_path/);
assert.match(frontend, /recoverActiveMediaJob/);
assert.match(frontend, /mediaStartLock/);
assert.match(frontend, /setMediaJob\(provisionalMediaJob\(\)\)/);
assert.match(frontend, /mediaRecoveryLoading/);
assert.match(frontend, /PREPARANDO COPIA\.\.\./);
assert.match(frontend, /COPIA MULTIMEDIA LISTA/);
assert.match(frontend, /EVIDENCIAS COPIADAS/);
assert.match(frontend, /DESCARGAR COPIA/);
assert.match(frontend, /mediaDownloadLock/);
assert.match(frontend, /RECOPILANDO EVIDENCIAS/);
assert.match(frontend, /GENERANDO ZIP/);
assert.match(frontend, /PREPARANDO ARCHIVO FINAL/);
assert.match(frontend, /Evidencias localizadas/);
assert.match(frontend, /ZIP generado/);
assert.match(frontend, /Copia multimedia lista/);
assert.doesNotMatch(frontend, /autoDownloadAttemptedRef/);
assert.doesNotMatch(frontend, /mediaJob\.estado !== 'completed'/);
assert.match(frontend, /mediaStartLock\.current = true/);
assert.match(frontend, /const active = await recoverActiveMediaJob\(\)/);
assert.match(frontend, /activeMediaStates\.includes\(mediaJob\?\.estado \|\| 'completed'\)/);
assert.doesNotMatch(frontend, /localStorage|sessionStorage/);
assert.match(migration, /CREATE TABLE IF NOT EXISTS public\.backup_jobs/); assert.match(migration, /backup_jobs_one_active_media_job/); assert.match(migration, /ENABLE ROW LEVEL SECURITY/);
assert.match(migration, /REVOKE ALL PRIVILEGES ON TABLE public\.backup_jobs FROM anon, authenticated/); assert.match(migration, /GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public\.backup_jobs TO service_role/); assert.doesNotMatch(migration, /INSERT INTO|UPDATE public\.|DELETE FROM/);
const signature = workerInvocationSignature('test-secret', '11111111-1111-4111-8111-111111111111', '22222222-2222-4222-8222-222222222222', '2026-08-10T12:05:00.000Z');
assert.equal(validWorkerSignature('test-secret', '11111111-1111-4111-8111-111111111111', '22222222-2222-4222-8222-222222222222', '2026-08-10T12:05:00.000Z', signature), true);
assert.equal(validWorkerSignature('test-secret', '11111111-1111-4111-8111-111111111111', 'different-actor', '2026-08-10T12:05:00.000Z', signature), false);
assert.equal(internalMediaDispatchOrigin({ rawUrl: 'https://deploy-preview-12--logistica-fernaguez-admin.netlify.app/.netlify/functions/admin-start-media-backup' } as any), 'https://deploy-preview-12--logistica-fernaguez-admin.netlify.app');
assert.equal(internalMediaDispatchOrigin({ rawUrl: 'https://admin.appvielha.com/.netlify/functions/admin-start-media-backup' } as any), 'https://admin.appvielha.com');
assert.equal(internalMediaDispatchOrigin({ rawUrl: 'https://app.appvielha.com/.netlify/functions/admin-start-media-backup' } as any), undefined);
assert.equal(internalMediaDispatchOrigin({ rawUrl: 'https://other--logistica-fernaguez-admin.netlify.app/.netlify/functions/admin-start-media-backup' } as any), undefined);
assert.equal(mediaZipFilename({ idLegible: 'OB-2026-0005', fechaTrabajo: '2026-08-07', type: 'fotos', sequence: 1, mime: 'image/jpeg' }), 'OB-2026-0005_2026-08-07_FOTO_01.jpg');
assert.equal(mediaZipFilename({ idLegible: 'OB-2026-0005', fechaTrabajo: '2026-08-07', type: 'fotos', sequence: 2, mime: 'image/jpeg' }), 'OB-2026-0005_2026-08-07_FOTO_02.jpg');
assert.equal(mediaZipFilename({ idLegible: 'OB-2026-0005', fechaTrabajo: '2026-08-07', type: 'facturas', sequence: 2, mime: 'application/pdf' }), 'OB-2026-0005_2026-08-07_FACTURA_02.pdf');
assert.equal(mediaZipFilename({ idLegible: 'OB-2026-0005', fechaTrabajo: '2026-08-07', type: 'firmas', sequence: 1, mime: 'image/png' }), 'OB-2026-0005_2026-08-07_FIRMA_01.png');
assert.equal(mediaZipFilename({ idLegible: 'OB-2026-0005', fechaTrabajo: null, type: 'fotos', sequence: 1, mime: 'image/webp' }), 'OB-2026-0005_SIN_FECHA_FOTO_01.webp');
assert.doesNotMatch(mediaZipFilename({ idLegible: 'OB-2026-0005', fechaTrabajo: '2026-08-07', type: 'fotos', sequence: 1, mime: 'image/jpeg' }), /71d7e24b-adca-4fb9-a7a8-fcbf36e06e5c/);
assert.equal(mediaZipFilename({ idLegible: '../OB-2026-0005', fechaTrabajo: '2026-08-07', type: 'fotos', sequence: 1, mime: 'image/jpeg' }).includes('/'), false);
assert.equal(verifyMediaBytes('image/gif', Buffer.from('GIF89a')), false);
assert.equal(verifyMediaBytes('image/jpeg', Buffer.from([0xff, 0xd8, 0xff, 0xd9])), true);
assert.equal(verifyMediaBytes('image/png', Buffer.from([137,80,78,71,13,10,26,10])), true);
assert.equal(verifyMediaBytes('image/webp', Buffer.from('RIFFxxxxWEBP')), true);
assert.equal(verifyMediaBytes('application/pdf', Buffer.from('%PDF-1.7')), true);
const synthetic = new JSZip(); synthetic.file('manifest.json', JSON.stringify({ medios_incluidos: true })); synthetic.file('media/OB-2026-0001/fotos/reporte-fotos-1.jpg', Buffer.from([0xff, 0xd8, 0xff, 0xd9])); const archive = await synthetic.generateAsync({ type: 'nodebuffer' }); const opened = await JSZip.loadAsync(archive); assert.equal(JSON.parse(await opened.file('manifest.json')!.async('text')).medios_incluidos, true); assert.equal(createHash('sha256').update(archive).digest('hex').length, 64);
console.log('admin media backup contract: passed');
