import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

const source = readFileSync(resolve(process.cwd(), 'src/pages/BackupCenter.tsx'), 'utf8');

assert.match(source, /in\('estado', \['Finalizada', 'Finalizado'\]\)/);
assert.match(source, /eq\('estado', 'Archivado'\)/);
assert.match(source, /rpc\('admin_archive_orders', \{ p_order_ids: orderIds \}\)/);
assert.match(source, /selectedArchiveIds/);
assert.match(source, /toggleAllArchiveOrders/);
assert.match(source, /ARCHIVAR \{selectedArchiveIds\.size\} SELECCIONADAS/);
assert.match(source, /rpc\('admin_restore_order', \{ p_order_id: orderId \}\)/);
assert.match(source, /RESTAURAR/);
assert.match(source, /VER DETALLE/);
assert.match(source, /Resumen de Obra Histórica/);
assert.match(source, /loadHistoricalOrderDetail/);
assert.match(source, /\.eq\('orden_id', order\.id\)/);
assert.match(source, /select\('id, orden_id, tecnico_id, fecha_trabajo, horas_trabajadas, notas, trabajo_realizado, material_utilizado, fotos_urls, creado_en'\)/);
assert.match(source, /rpc\('get_trabajadores_directory'\)/);
assert.match(source, /technicianNames\.set\(worker\.trabajador_id, workerName\)/);
assert.match(source, /if \(worker\.auth_user_id\) technicianNames\.set\(worker\.auth_user_id, workerName\)/);
assert.match(source, /logHistoricalDetailError\('directory', directoryError\)/);
assert.match(source, /logHistoricalDetailError\('reports', reportsByOrderId\.error\)/);
assert.match(source, /setArchiveError\('No se pudieron cargar las intervenciones de la obra archivada\. Inténtalo de nuevo\.'\)/);
assert.match(source, /logHistoricalDetailError\('transform', transformError\)/);
assert.match(source, /logHistoricalDetailError\('order', orderError/);
assert.match(source, /\.maybeSingle\(\)/);
assert.match(source, /select\('id, id_legible, cliente, aseguradora, poliza, estado, estado_previo, fecha_cierre, creado_en, direccion'\)/);
assert.match(source, /let resolvedAddress = order\.direccion\?\.trim\(\) \|\| null/);
assert.match(source, /from\('aseguradoras'\)[\s\S]*select\('direccion'\)[\s\S]*eq\('nombre', order\.cliente\)/);
assert.match(source, /logHistoricalDetailError\('client', customerError\)/);
assert.match(source, /direccion: resolvedAddress/);
assert.doesNotMatch(source, /CP: \{selectedHistoricalOrder\./);
assert.doesNotMatch(source, /codigo_postal/);
assert.doesNotMatch(source, /localidad/);
assert.doesNotMatch(source, /\.eq\('orden_id', order\.id_legible\)/);
assert.doesNotMatch(source, /trabajos_realizados/);
assert.doesNotMatch(source, /Aseguradora:/);
assert.doesNotMatch(source, /Póliza:/);
assert.match(source, /fecha_trabajo.*localeCompare.*creado_en/s);
assert.match(source, /Tiempo total: \{formatWorkHours\(historicalTotalHours\)\}/);
assert.match(source, /Trabajo realizado:/);
assert.match(source, /Materiales:/);
assert.match(source, /Fotos:/);
assert.match(source, /formatWorkDate\(report\.fecha_trabajo\)/);
assert.match(source, /report\.fotos_urls\?\.length \|\| 0/);
assert.match(source, /setSelectedHistoricalOrder\(null\)/);
assert.doesNotMatch(source, /compactado/);
assert.doesNotMatch(source, /from\('ordenes'\)\.update\(\{ estado: restoredState/);
assert.doesNotMatch(source, /from\('ordenes'\)\.update\(/);
