import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

const source = readFileSync(resolve(process.cwd(), '20260813_add_admin_archive_orders_rpc.sql'), 'utf8');

assert.match(source, /BEGIN;\s+CREATE OR REPLACE FUNCTION public\.admin_archive_orders/);
assert.match(source, /CREATE OR REPLACE FUNCTION public\.admin_archive_orders\(p_order_ids uuid\[\]\)/);
assert.match(source, /SECURITY DEFINER/);
assert.match(source, /SET search_path = ''/);
assert.match(source, /auth\.uid\(\)/);
assert.match(source, /public\.perfiles/);
assert.match(source, /public\.roles/);
assert.match(source, /rol\.nombre = 'Administrador'/);
assert.match(source, /AUTHENTICATION_REQUIRED/);
assert.match(source, /ADMINISTRATOR_REQUIRED/);
assert.match(source, /ORDER_IDS_REQUIRED/);
assert.match(source, /DUPLICATE_ORDER_IDS/);
assert.match(source, /ORDER_NOT_FOUND/);
assert.match(source, /FOR UPDATE/);
assert.match(source, /estado NOT IN \('Finalizada', 'Finalizado'\)/);
assert.match(source, /ORDERS_NOT_FINALIZED/);
assert.match(source, /SET estado_previo = estado,\s+estado = 'Archivado'/);
assert.match(source, /GET DIAGNOSTICS v_updated_count = ROW_COUNT/);
assert.match(source, /ARCHIVE_COUNT_MISMATCH/);
assert.match(source, /REVOKE ALL ON FUNCTION public\.admin_archive_orders\(uuid\[\]\) FROM PUBLIC/);
assert.match(source, /REVOKE EXECUTE ON FUNCTION public\.admin_archive_orders\(uuid\[\]\) FROM anon/);
assert.match(source, /GRANT EXECUTE ON FUNCTION public\.admin_archive_orders\(uuid\[\]\) TO authenticated/);
assert.match(source, /CREATE OR REPLACE FUNCTION public\.admin_restore_order\(p_order_id uuid\)/);
assert.match(source, /ORDER_ID_REQUIRED/);
assert.match(source, /WHERE id = p_order_id\s+FOR UPDATE/);
assert.match(source, /SET estado = COALESCE\(estado_previo, 'Finalizada'\),\s+estado_previo = NULL/);
assert.match(source, /ORDER_NOT_ARCHIVED/);
assert.match(source, /RESTORE_COUNT_MISMATCH/);
assert.match(source, /REVOKE ALL ON FUNCTION public\.admin_restore_order\(uuid\) FROM PUBLIC/);
assert.match(source, /REVOKE EXECUTE ON FUNCTION public\.admin_restore_order\(uuid\) FROM anon/);
assert.match(source, /GRANT EXECUTE ON FUNCTION public\.admin_restore_order\(uuid\) TO authenticated/);
assert.match(source, /GRANT EXECUTE ON FUNCTION public\.admin_restore_order\(uuid\) TO authenticated;\s+COMMIT;\s*$/);
assert.doesNotMatch(source, /\bDELETE\b/);
